### PR TITLE
Nnmf

### PR DESCRIPTION
**Pull request by gdkrmr**
fixed the method and the first set of unit tests

### CODE REVIEW

**Comment by topepo** [comment]
Excellent. Do you still want this since `NNLM` is back on CRAN? Personally, I think that this is better (but its your package). 

Also, I got the impression that I shouldn't commit Rd files to your repo. Was I reading into it too much?

**Comment by gdkrmr** [comment]
I like it the way it is now and because the `NNLM` authors were really slow to fix things I will stick with this. There is one larger issue I haven't looked into yet: Prediction needs `solve` and solve needs `crossprod(w)` to have full rank, see the second set of unit tests for a case where this happens.

**Comment by gdkrmr** [comment]
I just pushed to gdkrmr/nnmf and I get a strange failure on my computer:
`R CMD check --as-cran --timings` works fine, but
`R CMD check --run-donttest --run-dontrun --timings` gives the following error:

```
  OK: 247 SKIPPED: 0 FAILED: 1
  1. Failure: misc functions (@test_dimRedData.R#27) 
```

which tests the `nrow` function.

**Comment by gdkrmr** [comment]
well, tests seem to pass on travis, so if you have nothing to add I will merge my `nnmf` branch into `develop`

**Comment by topepo** [comment]
Can you test it using `devtools::build_win()`? It would be interesting to see what that does. 

Otherwise, sure. Merge away. Thanks!

**Comment by gdkrmr** [comment]
there were some issues, but it finally passes winbuilder.

**Pull request merged**
